# Generated by Django 3.2.7 on 2021-09-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20210916_1521'),
        ('checkout_20202020', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.producto'),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='cantMinima',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='dcto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='usuario',
            field=models.CharField(max_length=200),
        ),
    ]
