# Generated by Django 3.2.7 on 2021-09-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_20202020', '0002_auto_20210921_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
